namespace VisionMesh.Tests;

/// <summary>
/// Locates the JPEG fixtures generated by <c>tests/fixtures/generate.py</c>.
/// They are real files produced by a real encoder rather than hand-written byte arrays,
/// because the whole point of the decoder tests is to prove we agree with an actual encoder.
/// </summary>
internal static class Fixtures
{
    private static readonly Lazy<string> Root = new(Locate);

    public static string Path(string name) => System.IO.Path.Combine(Root.Value, name);

    public static byte[] Read(string name) => File.ReadAllBytes(Path(name));

    private static string Locate()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            var candidate = System.IO.Path.Combine(directory.FullName, "tests", "fixtures");
            if (Directory.Exists(candidate)) return candidate;
            directory = directory.Parent;
        }
        throw new DirectoryNotFoundException(
            "Could not find tests/fixtures. Run tests/fixtures/generate.py to create the JPEG fixtures.");
    }
}
